version: '3.6'

services:
  pokeagent:
    image: johncapobianco/pokeagent:pokeagent
    container_name: pokeagent
    restart: always
    build: 
      context: ./
      dockerfile: ./docker/Dockerfile   
    ports:
      - "8501:8501"